# -*- coding: utf-8 -*-
"""Installer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/173C7PpgcPmyEIsrNVxTv1Pz8HA4bv4FU
"""

!pip install python-docx
!pip install python-Levenshtein

import re
from google.colab import drive
drive.mount('/content/drive')

path_to_scripts = '/content/drive/Shareddrives/allographica/colab/scripts/'
path_to_docs = '/content/drive/Shareddrives/allographica/'   #INSERT FILE NAME AFTER allographica/

from drive.Shareddrives.allographica.colab.scripts.mia.transcoder import Transcoder
from drive.Shareddrives.allographica.colab.scripts.mia.aligner import SimEval
from drive.Shareddrives.allographica.colab.scripts.mia.aligner import StringSimEval
from drive.Shareddrives.allographica.colab.scripts.mia.aligner import ObjectAligner

grc2lat = Transcoder(path_to_scripts+'grc2lat.txt')
grc2simpLat = Transcoder(path_to_scripts+'grc2simpLat.txt')
simpLat2regex = Transcoder(path_to_scripts+'simpLat2regex.txt')

from docx import Document

# Get the name of the uploaded file
in_file_name = path_to_docs + ''         #INSERT FILE NAME into ''
in_file = open(in_file_name, encoding = 'utf-8')