# -*- coding: utf-8 -*-
"""layout_creator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qtSpXNB4p_JFm11I9tgdaT3dqt2_GJu9
"""

in_file_name = path_to_docs + ''     #INSERT FILE NAME into ''
in_file = open(in_file_name, encoding = 'utf-8')

# Read the contents of the .docx file and divide by lines
doc = Document(in_file_name)

def create_para_list(doc):
    run_list = []
    for para in doc.paragraphs:
        for run in para.runs:
            if run.font.superscript:
                run_list.append(f'{{{run.text}}}')
            else:
                run_list.append(run.text)
        run_list.append('\n')
    text = ' '.join(run_list)
    return text.split('\n')

para_list = create_para_list(doc)
para_list.pop()

for i, para in enumerate(para_list):
    if i > 0 and i % 2 == 0:
        transl = grc2lat.transcode(para)

        simp_transl = grc2simpLat.transcode(para)

        # Verifica se 'simp_transl' è una lista
        if isinstance(simp_transl, list):
            # Unisci gli elementi della lista in una stringa
            simp_transl = ''.join(simp_transl)

        regex = simpLat2regex.transcode(simp_transl)

        print(para)
        print(transl)
        print(simp_transl)
        print(regex)

# Aggiunta di controllo per evitare IndexError
        if i + 1 < len(para_list):
            print(para_list[i+1])
        else:
            print("Nessun elemento successivo")

        print()
in_file.close()