# -*- coding: utf-8 -*-
"""TEI_structure_creator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19boreh6VRVymYqX4eRXj-2a21SfPhr8o
"""

# Funzione per creare il file TEI
def create_tei_xml(paragraphs):
    TEI_NS = "http://www.tei-c.org/ns/1.0"
    XML_NS = "http://www.w3.org/XML/1998/namespace"
    NSMAP = {None: TEI_NS, 'xml': XML_NS}

    tei = etree.Element('TEI', nsmap=NSMAP)
    tei_header = etree.SubElement(tei, 'teiHeader')
    file_desc = etree.SubElement(tei_header, 'fileDesc')

    # Header
    title_stmt = etree.SubElement(file_desc, 'titleStmt')
    title = etree.SubElement(title_stmt, 'title')
    title.text = "Manuale per la costruzione delle navi"
    author = etree.SubElement(title_stmt, 'author')
    author.text = "Federico"
    publication_stmt = etree.SubElement(title_stmt, 'publicationStmt')
    pub = etree.SubElement(publication_stmt, 'p')
    pub.text = "Pubblicato da Camilla Granzotto, Federico Boschetti e Giulia Re"
    source_desc = etree.SubElement(file_desc, 'sourceDesc')
    desc = etree.SubElement(source_desc, 'p')
    desc.text = "Manoscritto allografico sulla costruzione delle navi"

    # Corpo
    text_element = etree.SubElement(tei, 'text')
    body_element = etree.SubElement(text_element, 'body')

    for para in paragraphs:
        body_element.append(para)

    return etree.tostring(tei, pretty_print=True, xml_declaration=True, encoding='UTF-8').decode('utf-8')

"""struttura di base dell'output tei-xml (source doc separato da text)."""