# -*- coding: utf-8 -*-
"""main_&_download_output

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nYna1XCJ33V2G_UMsmuBJxAH_rJU5xgx
"""

# Funzione principale
def main():
    # Percorso del file .docx
    input_docx = '' #INSERISCI PERCORSO
    intermediate_xml = 'output_initial.xml'
    final_xml = 'output_final.xml'

    try:
        doc = Document(input_docx)
    except FileNotFoundError:
        print(f"Errore: il file {input_docx} non è stato trovato.")
        return None

    # Crea file XML iniziale
    para_list = create_para_list_with_formatting(doc)
    xml_output = create_tei_xml(para_list)

    # Salva l'XML iniziale
    with open(intermediate_xml, "w", encoding="utf-8") as f:
        f.write(xml_output)
    print(f"File iniziale salvato: {intermediate_xml}")

    # Raffina l'XML
    refined_xml = refine_xml_language(xml_output)

    # Salva il file XML finale
    with open(final_xml, "w", encoding="utf-8") as f:
        f.write(refined_xml)
    print(f"File finale salvato: {final_xml}")

    # Controlla se il file esiste prima di scaricarlo
    if os.path.exists(final_xml):
        print(f"File finale trovato: {final_xml}. Preparazione per il download...")
        files.download(final_xml)
    else:
        print(f"Errore: il file {final_xml} non è stato trovato.")
        return None

    return final_xml

# Esegui la funzione principale
main()